/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Registered and JWT issued. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description Registration failed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login success and JWT issued. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                /** @description Missing email or password. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invalid credentials. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current logged-in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User profile. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserDataResponse"];
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logout and clear auth cookie */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmptyDataResponse"];
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campgrounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List campgrounds
         * @description Supports simple filtering and Mongo operators (`gt`, `gte`, `lt`, `lte`, `in`) via query string.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated fields. */
                    select?: string;
                    /** @description Comma-separated sort fields. */
                    sort?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Campground list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampgroundListResponse"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create campground
         * @description Admin role only.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CampgroundUpsertRequest"];
                };
            };
            responses: {
                /** @description Campground created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampgroundDataResponse"];
                    };
                };
                /** @description Invalid payload. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not admin. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Role forbidden. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campgrounds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get campground by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of campground. */
                    id: components["parameters"]["CampgroundEntityIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Campground details. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampgroundDataResponse"];
                    };
                };
                /** @description Invalid or missing campground. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Update campground
         * @description Admin or owner of campground.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of campground. */
                    id: components["parameters"]["CampgroundEntityIdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CampgroundUpsertRequest"];
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CampgroundDataResponse"];
                    };
                };
                /** @description Invalid request or missing campground. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not owner/admin. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete campground
         * @description Admin role only.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of campground. */
                    id: components["parameters"]["CampgroundEntityIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmptyDataResponse"];
                    };
                };
                /** @description Invalid or missing campground. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not admin. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campgrounds/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reviews for a campground
         * @description Returns active reviews (status `reviewed` and `review_isDeleted` not true) for the given campground,
         *     plus the computed `averageRating`. Supports `sort` and Mongo operator filters
         *     (e.g. `?review_rating[gte]=4`). Default sort is `-review_createdAt` (newest first).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated sort fields (e.g. `-review_createdAt`). */
                    sort?: string;
                    /** @description Operator filter, e.g. `?review_rating[gte]=4`. */
                    review_rating?: Record<string, never>;
                };
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of campground. */
                    id: components["parameters"]["CampgroundEntityIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Review list with average rating. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewListResponse"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campgrounds/{campgroundId}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bookings (scoped by role)
         * @description Requires authentication.
         *     - admin: sees all bookings
         *     - campOwner: sees bookings for owned campgrounds
         *     - user: sees own bookings
         */
        get: {
            parameters: {
                query?: {
                    select?: string;
                    sort?: string;
                    status?: "confirmed" | "checked-in" | "checked-out" | "cancelled";
                };
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of campground. */
                    campgroundId: components["parameters"]["CampgroundIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingListResponse"];
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create booking for campground */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of campground. */
                    campgroundId: components["parameters"]["CampgroundIdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BookingCreateRequest"];
                };
            };
            responses: {
                /** @description Booking created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingDataResponse"];
                    };
                };
                /** @description Validation or capacity error. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden for guest-booking role. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Campground not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookings (scoped by role) */
        get: {
            parameters: {
                query?: {
                    select?: string;
                    sort?: string;
                    status?: "confirmed" | "checked-in" | "checked-out" | "cancelled";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingListResponse"];
                    };
                };
                /** @description Unauthorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create booking (legacy route)
         * @deprecated
         * @description This route exists in code but creation logic expects `campgroundId` in path params.
         *     Prefer `POST /api/v1/campgrounds/{campgroundId}/bookings`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BookingCreateRequest"];
                };
            };
            responses: {
                /** @description Usually fails because campgroundId is missing. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export bookings as CSV
         * @description campOwner and admin only.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV file attachment. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                /** @description Not allowed for role user. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/today-checkouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get today's expected check-outs
         * @description campOwner and admin only.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Today checkout list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TodayCheckoutResponse"];
                    };
                };
                /** @description Not authorized for role user. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get booking by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of booking. */
                    id: components["parameters"]["BookingIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking details. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingDataResponse"];
                    };
                };
                /** @description Not authorized to view booking. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Update booking */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of booking. */
                    id: components["parameters"]["BookingIdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BookingUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingDataResponse"];
                    };
                };
                /** @description Validation or invalid status transition. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not authorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete booking */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of booking. */
                    id: components["parameters"]["BookingIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmptyDataResponse"];
                    };
                };
                /** @description Cannot delete due to status. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not authorized. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cancel booking */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of booking. */
                    id: components["parameters"]["BookingIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancelled. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingDataResponse"];
                    };
                };
                /** @description Already cancelled or started/completed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not authorized to cancel. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Check in booking
         * @description campOwner of the campground only.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of booking. */
                    id: components["parameters"]["BookingIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Checked in. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingDataResponse"];
                    };
                };
                /** @description Invalid timing/state or campground full. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not authorized. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Check out booking
         * @description campOwner of the campground only.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of booking. */
                    id: components["parameters"]["BookingIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Checked out. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingDataResponse"];
                    };
                };
                /** @description Cannot checkout before check-in or already checked out. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not authorized. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Create a review for a booking
         * @description User role only. Booking must be owned by the caller and have status `checked-out`.
         *     After success the booking status becomes `reviewed`.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of booking. */
                    id: components["parameters"]["BookingIdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewUpsertRequest"];
                };
            };
            responses: {
                /** @description Review created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingDataResponse"];
                    };
                };
                /** @description Not yet checked-out, already reviewed, or invalid rating. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not the booking owner, not a `user`, or booking is blocked from reviewing. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Booking not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a booking review (soft delete)
         * @description Soft-delete a review. Behavior depends on the caller:
         *     - **user (booking owner)**: clears the review and resets status to `checked-out` so the user can re-review.
         *     - **admin**: marks the booking `can-not-review`, permanently blocking further reviews.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of booking. */
                    id: components["parameters"]["BookingIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Review deleted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingDataResponse"];
                    };
                };
                /** @description No active review on this booking. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not the booking owner and not an admin. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Booking not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bookings/{id}/review/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update an existing booking review
         * @description User role only. Booking must be owned by the caller and currently have status `reviewed`
         *     with `review_isDeleted` not true.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description MongoDB ObjectId of booking. */
                    id: components["parameters"]["BookingIdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewUpsertRequest"];
                };
            };
            responses: {
                /** @description Review updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingDataResponse"];
                    };
                };
                /** @description No active review to update or invalid rating. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not the booking owner or not a `user`. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Booking not found. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Server error. */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @example 67cae6fd2e3d0f4b15d7e521 */
            _id?: string;
            /** @example John Smith */
            name?: string;
            /** @example 0898765432 */
            tel?: string;
            /**
             * Format: email
             * @example john.smith@example.com
             */
            email?: string;
            /**
             * @example user
             * @enum {string}
             */
            role?: "user" | "admin" | "campOwner";
            /** Format: date-time */
            createdAt?: string;
        };
        Campground: {
            /** @example 67cae8f12e3d0f4b15d7e70f */
            _id?: string;
            /** @example Pine Mountain Camp */
            name?: string;
            /** @example 123 Mountain Road */
            address?: string;
            /** @example Chiang Mai */
            district?: string;
            /** @example Chiang Mai */
            province?: string;
            /** @example 50000 */
            postalcode?: string;
            /** @example 0811111111 */
            tel?: string;
            /** @example North */
            region?: string;
            /** @example 50 */
            capacity?: number;
            /** @example 67cae6fd2e3d0f4b15d7e5f0 */
            owner?: string;
            bookings?: (string | components["schemas"]["Booking"])[];
        };
        Booking: {
            /** @example 67caf1232e3d0f4b15d80271 */
            _id?: string;
            /** Format: date-time */
            checkInDate?: string;
            /** Format: date-time */
            checkOutDate?: string;
            /** Format: date-time */
            actualCheckIn?: string | null;
            /** Format: date-time */
            actualCheckOut?: string | null;
            /** @example 2 */
            nightsCount?: number;
            user?: (string | components["schemas"]["User"]) | null;
            /** @example Tom Hardy */
            guestName?: string | null;
            /** @example 0612345678 */
            guestTel?: string | null;
            campground?: string | components["schemas"]["Campground"];
            /**
             * @default confirmed
             * @enum {string}
             */
            status: "confirmed" | "checked-in" | "checked-out" | "cancelled" | "reviewed" | "can-not-review";
            /** Format: date-time */
            cancelledAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** @example 5 */
            review_rating?: number | null;
            /** @example Great campground, would visit again. */
            review_comment?: string | null;
            /** Format: date-time */
            review_createdAt?: string | null;
            /** @default false */
            review_isDeleted: boolean;
        };
        RegisterRequest: {
            name: string;
            tel: string;
            /** Format: email */
            email: string;
            password: string;
            /**
             * @default user
             * @enum {string}
             */
            role: "user" | "admin" | "campOwner";
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        CampgroundUpsertRequest: {
            name: string;
            address: string;
            district: string;
            province: string;
            postalcode: string;
            tel: string;
            region: string;
            /** @default 5 */
            capacity: number;
            /** @description User id with role campOwner. */
            owner: string;
        };
        /**
         * @description For regular self-booking, do not send `guestName` and `guestTel`.
         *     For guest booking, send both `guestName` and `guestTel` (allowed only for admin or campground owner).
         */
        BookingCreateRequest: {
            /**
             * Format: date
             * @example 2026-05-01
             */
            checkInDate: string;
            /**
             * Format: date
             * @example 2026-05-03
             */
            checkOutDate: string;
            guestName?: string | null;
            guestTel?: string | null;
        };
        BookingUpdateRequest: {
            /** Format: date */
            checkInDate?: string;
            /** Format: date */
            checkOutDate?: string;
            guestName?: string | null;
            guestTel?: string | null;
            /** @enum {string} */
            status?: "confirmed" | "checked-in" | "checked-out" | "cancelled" | "reviewed" | "can-not-review";
        };
        ReviewUpsertRequest: {
            /** @example 5 */
            review_rating: number;
            /** @example Loved the lakeside view. */
            review_comment?: string | null;
        };
        ReviewListResponse: {
            /** @example true */
            success?: boolean;
            /** @example 3 */
            count?: number;
            /**
             * Format: float
             * @example 4.67
             */
            averageRating?: number;
            data?: components["schemas"]["Booking"][];
        };
        TokenResponse: {
            /** @example true */
            success?: boolean;
            token?: string;
        };
        EmptyDataResponse: {
            /** @example true */
            success?: boolean;
            data?: Record<string, never>;
        };
        ErrorResponse: {
            /** @example false */
            success?: boolean;
            /** @example Not authorized to access this route */
            message?: string;
            /** @example Registration failed */
            error?: string;
        };
        UserDataResponse: {
            /** @example true */
            success?: boolean;
            data?: components["schemas"]["User"];
        };
        CampgroundListResponse: {
            /** @example true */
            success?: boolean;
            /** @example 10 */
            count?: number;
            data?: components["schemas"]["Campground"][];
        };
        CampgroundDataResponse: {
            /** @example true */
            success?: boolean;
            data?: components["schemas"]["Campground"];
        };
        BookingListResponse: {
            /** @example true */
            success?: boolean;
            /** @example 2 */
            count?: number;
            data?: components["schemas"]["Booking"][];
        };
        TodayCheckoutResponse: {
            /** @example true */
            success?: boolean;
            /** @example 2 */
            count?: number;
            /** @example 2026-04-14 */
            date?: string;
            data?: components["schemas"]["Booking"][];
        };
        BookingDataResponse: {
            /** @example true */
            success?: boolean;
            data?: components["schemas"]["Booking"];
        };
    };
    responses: never;
    parameters: {
        /** @description MongoDB ObjectId of campground. */
        CampgroundIdParam: string;
        /** @description MongoDB ObjectId of booking. */
        BookingIdParam: string;
        /** @description MongoDB ObjectId of campground. */
        CampgroundEntityIdParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
