/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Alice Smith */
                        name: string;
                        /** @example 0812345678 */
                        tel: string;
                        /**
                         * Format: email
                         * @example alice@example.com
                         */
                        email: string;
                        /**
                         * Format: password
                         * @example secret123
                         */
                        password: string;
                        /**
                         * @default user
                         * @enum {string}
                         */
                        role?: "user" | "admin" | "campOwner";
                    };
                };
            };
            responses: {
                /** @description User registered successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in and receive a JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example alice@example.com
                         */
                        email: string;
                        /**
                         * Format: password
                         * @example secret123
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current logged-in user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log out (clears the token cookie) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campgrounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all campgrounds
         * @description Public endpoint. Supports advanced filtering, field selection, sorting,
         *     and pagination via query parameters.
         *
         *     **Filtering:** any Campground field can be used as a filter. MongoDB
         *     comparison operators are supported with the syntax
         *     `?capacity[gte]=5`.
         *
         *     **Operators:** `gt`, `gte`, `lt`, `lte`, `in`
         */
        get: {
            parameters: {
                query?: {
                    /** @description Comma-separated fields to return (e.g. `name,province`) */
                    select?: string;
                    /** @description Comma-separated sort fields. Prefix with `-` for descending (e.g. `-capacity,name`) */
                    sort?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of campgrounds */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            count?: number;
                            data?: components["schemas"]["Campground"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a campground
         * @description Requires `admin` role.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CampgroundInput"];
                };
            };
            responses: {
                /** @description Campground created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Campground"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campgrounds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Campground MongoDB ObjectId */
                id: string;
            };
            cookie?: never;
        };
        /** Get a single campground */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Campground MongoDB ObjectId */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Campground detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Campground"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        /**
         * Update a campground
         * @description Requires `admin` or `campOwner` (owner of this campground).
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Campground MongoDB ObjectId */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CampgroundInput"];
                };
            };
            responses: {
                /** @description Campground updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Campground"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        post?: never;
        /**
         * Delete a campground
         * @description Requires `admin` role. Also deletes all bookings associated with the
         *     campground.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Campground MongoDB ObjectId */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Campground deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bookings (scoped by role)
         * @description - `admin` — all bookings
         *     - `campOwner` — bookings for their campgrounds
         *     - `user` — only their own bookings
         *
         *     Supports the same filtering, sorting, and field-selection query
         *     parameters as `/campgrounds`.
         */
        get: {
            parameters: {
                query?: {
                    select?: string;
                    sort?: string;
                    /** @description Filter by booking status */
                    status?: "confirmed" | "checked-in" | "checked-out" | "cancelled";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of bookings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            count?: number;
                            data?: components["schemas"]["Booking"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export bookings as CSV
         * @description Requires `admin` or `campOwner` role.
         *     - `admin` — exports all bookings
         *     - `campOwner` — exports bookings for their campgrounds
         *
         *     Returns a CSV file download.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Booking MongoDB ObjectId */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get a single booking
         * @description Accessible by the booking owner, the campground owner, or `admin`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Booking MongoDB ObjectId */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Booking"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Update a booking
         * @description Accessible by the booking owner, the campground owner, or `admin`.
         *     If updating dates, both `checkInDate` and `checkOutDate` must be
         *     provided together. Capacity is re-checked on date changes.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Booking MongoDB ObjectId */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BookingInput"];
                };
            };
            responses: {
                /** @description Booking updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Booking"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /**
         * Delete a booking
         * @description Accessible by the booking owner, the campground owner, or `admin`.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Booking MongoDB ObjectId */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Cancel a booking
         * @description Accessible by the booking owner, the campground owner, or `admin`.
         *     Cannot cancel a booking with status `checked-in` or `checked-out`.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Booking"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Check in a guest
         * @description Requires `campOwner` role (owner of the booking's campground).
         *     Hard limit: a campground may have at most **5** simultaneous
         *     `checked-in` bookings.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Checked in successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Booking"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Check out a guest
         * @description Requires `campOwner` role (owner of the booking's campground).
         *     The booking must already be checked in and the stay must have started.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Checked out successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Booking"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campgrounds/{campgroundId}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a booking for a campground
         * @description All authenticated roles can create a booking.
         *
         *     **Self-booking** (default): the booking is linked to the authenticated user.
         *
         *     **Guest booking** (`campOwner` / `admin` only): supply `guestName` and
         *     `guestTel` in the request body. `user` is set to `null`.
         *
         *     **Constraints:**
         *     - Stay must be 1–3 nights.
         *     - Campground capacity must not be exceeded on any night of the stay.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Campground MongoDB ObjectId */
                    campgroundId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BookingInput"];
                };
            };
            responses: {
                /** @description Booking created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            data?: components["schemas"]["Booking"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @example 6627c1e8f2a3b4c5d6e7f8a9 */
            _id?: string;
            /** @example Alice Smith */
            name?: string;
            /** @example 0812345678 */
            tel?: string;
            /**
             * Format: email
             * @example alice@example.com
             */
            email?: string;
            /**
             * @example user
             * @enum {string}
             */
            role?: "user" | "admin" | "campOwner";
            /** Format: date-time */
            createdAt?: string;
        };
        Campground: {
            /** @example 6627c2a0f2a3b4c5d6e7f8b1 */
            _id?: string;
            /** @example Pine Ridge Camp */
            name?: string;
            /** @example 123 Forest Road */
            address?: string;
            /** @example Mae Rim */
            district?: string;
            /** @example Chiang Mai */
            province?: string;
            /** @example 50180 */
            postalcode?: string;
            /** @example 053123456 */
            tel?: string;
            /** @example North */
            region?: string;
            /**
             * @default 5
             * @example 10
             */
            capacity: number;
            /**
             * @description User ID of the campground owner
             * @example 6627c1e8f2a3b4c5d6e7f8a9
             */
            owner?: string;
            /** @description Virtual field — populated on GET requests */
            bookings?: components["schemas"]["Booking"][];
        };
        CampgroundInput: {
            /** @example Pine Ridge Camp */
            name: string;
            /** @example 123 Forest Road */
            address: string;
            /** @example Mae Rim */
            district: string;
            /** @example Chiang Mai */
            province: string;
            /** @example 50180 */
            postalcode: string;
            /** @example 053123456 */
            tel: string;
            /** @example North */
            region: string;
            /**
             * @default 5
             * @example 10
             */
            capacity: number;
            /** @example 6627c1e8f2a3b4c5d6e7f8a9 */
            owner: string;
        };
        Booking: {
            /** @example 6627c3b0f2a3b4c5d6e7f8c2 */
            _id?: string;
            /**
             * Format: date
             * @example 2026-05-01
             */
            checkInDate?: string;
            /**
             * Format: date
             * @example 2026-05-03
             */
            checkOutDate?: string;
            /** Format: date-time */
            actualCheckIn?: string | null;
            /** Format: date-time */
            actualCheckOut?: string | null;
            /** @example 2 */
            nightsCount?: number;
            /**
             * @description User ID — null for guest bookings
             * @example 6627c1e8f2a3b4c5d6e7f8a9
             */
            user?: string | null;
            /**
             * @description Required for guest bookings (campOwner/admin only)
             * @example John Guest
             */
            guestName?: string | null;
            /** @example 0898765432 */
            guestTel?: string | null;
            campground?: string | components["schemas"]["Campground"];
            /**
             * @default confirmed
             * @example confirmed
             * @enum {string}
             */
            status: "confirmed" | "checked-in" | "checked-out" | "cancelled";
            /** Format: date-time */
            cancelledAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        BookingInput: {
            /**
             * Format: date
             * @example 2026-05-01
             */
            checkInDate: string;
            /**
             * Format: date
             * @example 2026-05-03
             */
            checkOutDate: string;
            /**
             * @description Required together with guestTel for a guest booking
             * @example John Guest
             */
            guestName?: string;
            /** @example 0898765432 */
            guestTel?: string;
        };
        SuccessEnvelope: {
            /** @example true */
            success?: boolean;
        };
        ErrorResponse: {
            /** @example false */
            success?: boolean;
            /** @example Error description */
            message?: string;
        };
        AuthResponse: {
            /** @example true */
            success?: boolean;
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
            token?: string;
        };
    };
    responses: {
        /** @description Missing or invalid authentication token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authenticated but not authorised for this action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
